# Generated by Django 3.2.9 on 2022-02-03 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_line_linedata_spare_sub_assembly'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sub_assembly',
            name='component',
        ),
        migrations.AddField(
            model_name='linedata',
            name='spare',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.spare'),
        ),
    ]
