# Generated by Django 3.2.9 on 2022-02-04 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_linedata_spare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='line',
            field=models.ForeignKey(default='12m', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.line'),
        ),
        migrations.AlterField(
            model_name='linedata',
            name='part',
            field=models.ForeignKey(default='conveyor', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.part'),
        ),
    ]
