# Generated by Django 3.2.9 on 2022-02-04 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20220204_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linedata',
            name='sub_assembly',
            field=models.ForeignKey(default='carrier', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.sub_assembly'),
        ),
        migrations.AlterField(
            model_name='spare',
            name='part',
            field=models.ForeignKey(default='conveyor', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.part'),
        ),
        migrations.AlterField(
            model_name='sub_assembly',
            name='part',
            field=models.ForeignKey(default='conveyor', on_delete=django.db.models.deletion.SET_DEFAULT, to='api.part'),
        ),
    ]
